### ISSUE TITLE
Issues  installing ubuntu on Macbook Pro's VirtualBox...

### ISSUE THREAD

**Issue by ijawadi** [moezali1/MMA865#5]
I have a MacPro (Intel chipset).  I installed VirtualBox and downloaded “ubuntu-20.04.3-desktop-amd64”. This is the latest version (your instruction shows “ubuntu-20.04.2-”
The issue that I am experiencing is when I start my virtual box, unlike what you the recoding shows, it doesn’t detect the  .iso file and all I see is a blank screen…
How can I manually install the OS by pointing to the downloaded file?
I appreciate your help,

**Comment by Rjotsin** [comment]
Hi, since we won't need virtualbox for a while, might make sense to tackle this together in office hours.

Does this screen pop up at all when you start your VM? If not my first try would be to remake the VM in Video 3. another way is to go to Storage in Settings and point "Controller: IDE" to the iso and see if that works
![image](https://user-images.githubusercontent.com/18150981/132033145-c940f286-9ef2-4dd9-afdb-06487422b85d.png)

**Comment by ijawadi** [comment]
> Hi, since we won't need virtualbox for a while, might make sense to tackle this together in office hours.
> 
> Does this screen pop up at all when you start your VM? If not my first try would be to remake the VM in Video 3. another way is to go to Storage in Settings and point "Controller: IDE" to the iso and see if that works
> ![image](https://user-images.githubusercontent.com/18150981/132033145-c940f286-9ef2-4dd9-afdb-06487422b85d.png)

Agreed.  Let's synch up on the next office hours session.

**Comment by Rjotsin** [comment]
@ijawadi did you try out the solutions I outlined? Does the screen pop up like I asked?

**Comment by Rjotsin** [comment]
Can you close this ticket @ijawadi
